### ISSUE TITLE
2024-09-10-ds-rss-masterclass TODO

### ISSUE THREAD

**Issue by JaroCamphuijsen** [esciencecenter-digital-skills/research-software-support#107]
This issue lists to-do items that should be completed before the masterclass takes off:

- [ ] Define exercises for three weeks in-between 
  - [ ] One related to Research Software
  - [ ] One related to FAIR Software
  - [ ] Making a Software management plan (SMP module)
- [ ] Finish the Version Control module
- [ ] Finish the software documentation module
- [ ]
