### ISSUE TITLE
Attract more users

### ISSUE THREAD

**Issue by svenvanderburg** [esciencecenter-digital-skills/research-software-support#109]
It would be great if we can have more people using this lesson material. We could make the lesson more visible by:

```[tasklist]
### Tasks
- [ ] Add banner with request for testers in lesson website
- [ ] Make README attractive for new users
- [ ] Add beta pilot tester feedback form
- [ ] Write a short advertisement text attracting new users
- [ ] Write a short blogpost
```
